
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace BruetforcePassCheckerTUI {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyView : Terminal.Gui.Window {

        private Terminal.Gui.ColorScheme greyOnBlack;

        private Terminal.Gui.ColorScheme tgDefault;

        private Terminal.Gui.ColorScheme greenOnBlack;

        private Terminal.Gui.Window window;

        private Terminal.Gui.Label label2;

        private Terminal.Gui.Label label3;

        //Buttons
        private Terminal.Gui.Button buttonNewBase;
        private Terminal.Gui.Button buttonStart;

        private Terminal.Gui.Label label;

        private Terminal.Gui.TextField textField;

        private Terminal.Gui.TableView tableView;

        private void InitializeComponent()
        {
            this.tableView = new Terminal.Gui.TableView();
            this.buttonStart = new Terminal.Gui.Button();
            this.textField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.buttonNewBase = new Terminal.Gui.Button();
            this.label3 = new Terminal.Gui.Label();
            this.label2 = new Terminal.Gui.Label();
            this.window = new Terminal.Gui.Window();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.window.Width = 65;
            this.window.Height = 22;
            this.window.X = 1;
            this.window.Y = 0;
            this.window.Visible = true;
            this.window.ColorScheme = this.tgDefault;
            this.window.Modal = false;
            this.window.IsMdiContainer = false;
            this.window.Data = "window";
            this.window.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.window.Border.Effect3D = false;
            this.window.Border.Effect3DBrush = null;
            this.window.Border.DrawMarginFrame = true;
            this.window.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Title = "";
            this.Add(this.window);
            this.label2.Width = 4;
            this.label2.Height = 1;
            this.label2.X = 0;
            this.label2.Y = 0;
            this.label2.Visible = true;
            this.label2.Data = "label2";
            this.label2.Text = "Эта утилита предназначена для проверки стойкости пароля ";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.label2);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 26;
            this.label3.Y = 1;
            this.label3.Visible = true;
            this.label3.Data = "label3";
            this.label3.Text = "к методу прямого перебора (брутфорс)";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.label3);
            this.buttonNewBase.Width = 30;
            this.buttonNewBase.Height = 1;
            this.buttonNewBase.X = -1;
            this.buttonNewBase.Y = 3;
            this.buttonNewBase.Visible = true;
            this.buttonNewBase.ColorScheme = this.tgDefault;
            this.buttonNewBase.Data = "button";
            this.buttonNewBase.Text = "Добавить базу для проверки";
            this.buttonNewBase.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonNewBase.IsDefault = false;
            this.window.Add(this.buttonNewBase);
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 17;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "Введите пароль";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.label);
            this.textField.Width = Dim.Percent(50f);
            this.textField.Height = 10;
            this.textField.X = 1;
            this.textField.Y = 18;
            this.textField.Visible = true;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.window.Add(this.textField);
            this.buttonStart.Width = 19;
            this.buttonStart.Height = 1;
            this.buttonStart.X = 44;
            this.buttonStart.Y = 18;
            this.buttonStart.Visible = true;
            this.buttonStart.Data = "button2";
            this.buttonStart.Text = "Начать проверку";
            this.buttonStart.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.buttonStart.IsDefault = false;
            this.window.Add(this.buttonStart);
            this.tableView.Width = 50;
            this.tableView.Height = 5;
            this.tableView.X = 1;
            this.tableView.Y = 22;
            this.tableView.Visible = false;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableColumn0;
            tableViewTableColumn0 = new System.Data.DataColumn();
            tableViewTableColumn0.ColumnName = "Column 0";
            tableViewTable.Columns.Add(tableViewTableColumn0);
            System.Data.DataColumn tableViewTableColumn1;
            tableViewTableColumn1 = new System.Data.DataColumn();
            tableViewTableColumn1.ColumnName = "Column 1";
            tableViewTable.Columns.Add(tableViewTableColumn1);
            System.Data.DataColumn tableViewTableColumn2;
            tableViewTableColumn2 = new System.Data.DataColumn();
            tableViewTableColumn2.ColumnName = "Column 2";
            tableViewTable.Columns.Add(tableViewTableColumn2);
            System.Data.DataColumn tableViewTableColumn3;
            tableViewTableColumn3 = new System.Data.DataColumn();
            tableViewTableColumn3.ColumnName = "Column 3";
            tableViewTable.Columns.Add(tableViewTableColumn3);
            this.tableView.Table = tableViewTable;
            this.Add(this.tableView);
        }
    }
}
